# Generated by Django 5.2 on 2025-06-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
